// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "CREATE USERS",
    id: "63b9304c-eba2-4c3e-ba1a-42199d1af65e",
    method: "POST",
    address: "https://reqres.in/api/users",
    data: '{\r\n    "name": "morpheus",\r\n    "job": "leader"\r\n}',
    post(response) {
      var obj = JSON.parse(responseBody);
      pm.environment.set("idUser", obj.id);

      pm.test("Status code is 201", function() {
        pm.response.to.have.status(201);
      });
    }
  });

  postman[Request]({
    name: "LIST USER",
    id: "093e4bce-8787-4b66-9b52-fdad7006ac06",
    method: "GET",
    address: "https://reqres.in/api/users/{{idUser}}",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "DELETE USER",
    id: "c1cdd68a-af69-4eea-9e48-93b6ce2a6dc2",
    method: "DELETE",
    address: "https://reqres.in/api/users/3",
    post(response) {
      pm.test("Status code is 204", function() {
        pm.response.to.have.status(204);
      });
    }
  });

  postman[Request]({
    name: "Login",
    id: "812833df-750d-47a7-b817-547772ab0134",
    method: "POST",
    address: "https://reqres.in/api/login",
    data:
      '{\n    "email": "george.bluth@reqres.in",\n    "password": "pass123"\n}'
  });
}
